/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat;
import java.io.*;
import java.net.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Administrator
 */
public class Jclient extends javax.swing.JFrame {
    final static int ServerPort = 1234; 

    /**
     * Creates new form Jclient
     */
    public Jclient() {
        initComponents();
        chattext.setEditable(false);
         class Listen extends Thread {

            public Listen() {
                start();
            }

            @Override
            public void run() {
                try {
                    joinserver("127.0.0.1");
                } catch (IOException ex) {
                    Logger.getLogger(Jclient.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        new Listen();
    }
    public Jclient(String ipad) {
        initComponents();
       chattext.setEditable(false);
         class join extends Thread {

            public join() {
                start();
            }

            @Override
            public void run() {
                try {
                    joinserver(ipad);
                } catch (IOException ex) {
                    Logger.getLogger(Jclient.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        new join();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        chattext = new javax.swing.JTextArea();
        mess = new javax.swing.JTextField();
        sendmess = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chattext.setColumns(20);
        chattext.setRows(5);
        jScrollPane1.setViewportView(chattext);

        mess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendmessActionPerformed(evt);
            }
        });

        sendmess.setText("Gửi");
        sendmess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendmessActionPerformed(evt);
            }
        });

        logout.setText("Thoát");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mess, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sendmess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mess)
                    .addComponent(sendmess, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendmessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendmessActionPerformed
        // TODO add your handling code here:
         msg=mess.getText();
         try { 
                        // write on the output stream 
                        dos.writeUTF(msg); 
                    } catch (IOException e) { 
                        e.printStackTrace(); 
                    }   
         mess.setText("");
    }//GEN-LAST:event_sendmessActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
         try { 
                        // write on the output stream 
                        dos.writeUTF("logout"); 
                    } catch (IOException e) { 
                        e.printStackTrace(); 
                    }   
         this.dispose();
            jmain main=new jmain();
            main.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public  void main(String args[])   {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
             public void run() {
       
        new Jclient().setVisible(true);
             }
         });

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chattext;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JTextField mess;
    private javax.swing.JButton sendmess;
    // End of variables declaration//GEN-END:variables
 private String msg=null;
 Boolean ser = true;
public void joinserver(String ipad) throws UnknownHostException, IOException {
    //System.out.println("aaaa");
    //Scanner scn = new Scanner(System.in); 
        // thiết lập kết nối
        Socket s = new Socket(ipad, ServerPort); 
        // obtaining input and out streams 
         dis = new DataInputStream(s.getInputStream()); 
         dos = new DataOutputStream(s.getOutputStream()); 
        
        
        // sendMessage thread 
  
        // readMessage thread 
        Thread readMessage = new Thread(new Runnable()  
        { 
            @Override
            public void run() { 
                while (true) { 
                    try { 
                        // read the message sent to this client 
                        String msg = dis.readUTF(); 
                        chattext.setText(chattext.getText()+msg+"\n");
                        System.out.println(msg); 
                    } catch (IOException e) {  
                        e.printStackTrace(); 
                    } 
                } 
            } 
        }); 
  
       // sendMessage.start(); 
        readMessage.start();
}
         DataInputStream dis = null; 
         DataOutputStream dos = null; 
}